cham/lesson4/rails-app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "pages#home"
  get 'about', to: 'pages#about'
  resources :articles
  
  get "signup", to: 'users#new'
  resources :users, expect: [:new]
end

cham/lesson4/rails-app/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
  validates :description, presence: true, length: { minimum: 6, maximum: 300 }
end

cham/lesson4/rails-app/app/models/user.rb
class User < ApplicationRecord
  EMAIL_VALID_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  has_many :articles
  # 存在していること
  # 重複作成できないこと
  # 長さ 3 ~25
  validates :username, presence: true, uniqueness: true, length: { in: 3..25 }

  # 存在していること
  # 長さの最大 100
  # emailの形式に合っていること
  validates :email, presence: true, length: { maximum: 100 }, format: { with: EMAIL_VALID_REGEX,
    message: "pattern is not valid" }


  before_save { self.email = email.downcase }

  has_secure_password
end

cham/lesson4/rails-app/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.order(updated_at: :desc)
  end

  def new
    @article = Article.new
  end

  def show
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    # TODO: ログイン機能できる際に対応する
    @article.user = User.first
    if @article.save
      flash[:notice] = "Article created Successfully"
    redirect_to @article
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article updated Successfully"
    redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

end

cham/lesson4/rails-app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def about

  end
end

cham/lesson4/rails-app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
 
  def index
    @users = User.order(updated_at: :desc)
  end

  def new
    @user = User.new
  end

  def show
    @articles = @user.articles
  end

  def edit
  end

  def create
    @user = User.new(user_param)
    if @user.save!
      flash[:notice] = "Welcome #{@user.username}, you have sign up successfully"
      redirect_to articles_path
    else
      render :new
    end
  end

  def update
    if @user.update(user_param)
      flash[:notice] = "update profile successfully"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:notice] = "user profile deleted successfully"
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_param
    permitted = [:username, :email]
    permitted << :password_digest if params[:user][:password_digest].present?
    params.require(:user).permit(permitted)
  end
end

cham/lesson4/rails-app/app/views/articles/_articles.html.erb
<% @articles.each do |article|%>
<tr>
  <td><%= article.title %></td>
  <td><%= article.description %></td>
  <td><%= article.user.username %></td>
  <td><%= link_to "Edit", edit_article_path(article) %></td>
  <td><%= link_to "Show", article_path(article) %></td>
  <td><%= button_to "Delete", article_path(article), method: :delete, data: { turbo_confirm: "Are You Sure!" } %></td>
</tr>
<% end%>

cham/lesson4/rails-app/app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
  <div>
    <%= form.label :title %>
  </div>
  <br/>
  <div>
    <%= form.text_field :title %>
  </div>
  <br/>
  <div>
    <%= form.label :description %>
  </div>
  <br/>
  <div>
    <%= form.text_field :description %>
  </div>
   <br/>
  <%= form.submit %>
<% end %>

cham/lesson4/rails-app/app/views/articles/edit.html.erb
<h1>Edit a New Article</h1>
<%= render "form" %>
<p><%= link_to "Cancel and Back to Articles", articles_path %></p>
<p><%= button_to "Delete", article_path(@article), method: :delete, data: { turbo_confirm: "Are You Sure!" } %></p>

cham/lesson4/rails-app/app/views/articles/index.html.erb
<h1>Article List</h1>
<p><%= link_to "Create New Article", new_article_path %></p>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Author</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>
  <tbody>
    <%= render "articles" %>
  </tbody>
</table>
<p><%= link_to "Back to HomePage", root_path %></p>

cham/lesson4/rails-app/app/views/articles/new.html.erb
<h1>Create a New Article</h1>
<%= render "form" %>
<p><%= link_to "Cancel and Back to Articles", articles_path %></p>

cham/lesson4/rails-app/app/views/articles/show.html.erb
<h1>Article Detail</h1>
<p><strong>Title:</strong><%= @article.title %></p>
<p><strong>Description:</strong><%= @article.description %></p>
<p><strong>Description:</strong><%= @article.user.username %></p>
<p><%= link_to "Back to Articles", articles_path %></p>
<p><%= button_to "Delete", article_path(@article), method: :delete, data: { turbo_confirm: "Are You Sure!" } %></p>

cham/lesson4/rails-app/app/views/pages/about.html.erb
<h1>About Page</h1>
<p><%= link_to "Back to HomePage", root_path %></p>

cham/lesson4/rails-app/app/views/pages/home.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand">BubuDaBbBu</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to "Articles", articles_path, class: "nav-link active" %>
        <%= link_to "About Us", about_path,class: "nav-link" %>
      </div>
    </div>
  </div>
</nav>

cham/lesson4/rails-app/app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |form| %>
  <div>
    <%= form.label :username %>
  </div>
  <br/>
  <div>
    <%= form.text_field :username %>
  </div>
  <br/>
  <div>
    <%= form.label :email %>
  </div>
  <br/>
  <div>
    <%= form.text_field :email %>
  </div>
  <div>
    <%= form.label :password %>
  </div>
  <br/>
  <div>
    <%= form.password_field :password_digest %>
  </div>
   <br/>
  <%= form.submit(@user.new_record? ? "sign up" : "update account")  %>
<% end %>

cham/lesson4/rails-app/app/views/users/edit.html.erb
<h1>Edit Profile</h1>
<%= render "form" %>
<p><%= link_to "Cancel and Back to Users", users_path %></p>

cham/lesson4/rails-app/app/views/users/index.html.erb
<h1>Users Profiles</h1>
<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Email</th>
      <th>Article Number</th>
      <th colspan="2">Profile</th>
      <th>Joins</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user|%>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= pluralize(user.articles.count, "article")%></td>
      <td><%= link_to "Edit", edit_user_path(user) %></td>
      <td><%= link_to "Show", user_path(user) %></td>
      <td><%= "#{time_ago_in_words(user.created_at)} ago" %></td>
    </tr>
    <% end%>
  </tbody>
</table>
<p><%= link_to "Back to Articles", articles_path %></p>

cham/lesson4/rails-app/app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render "form" %>
<p><%= link_to "Cancel and Back to Articles", articles_path %></p>

cham/lesson4/rails-app/app/views/users/show.html.erb
<h1>Users Profiles</h1>
<p><strong>User Name:</strong><%= @user.username %></p>
<p><strong>Email:</strong><%= @user.email %></p>
<p><%= link_to "Back to Users", users_path %></p>
<%= render "articles/articles" %>